### PR TITLE
Removed 'new Function(...)' to avoid Content Security Policy (CSP) violation

### PR DESCRIPTION
**Pull request by tdelmas**
Same idea than #6 
Will help fix partially https://github.com/plotly/plotly.js/issues/897 for example

### CODE REVIEW

**Comment by ksk385** [comment]
We are facing this issue using plotly as well, can this be merged?

**Comment by archmoj** [comment]
ping @mikolalysenko

**Comment by archmoj** [comment]
Thanks @mikolalysenko for merging & publishing v2.0.5 to the npm. 
I thought now you simply want to `git push` to update the github master.
Also you could close #6 which is a duplicate.

**Comment by tdelmas** [comment]
Thank you @mikolalysenko !

**Pull request merged**
